datadog:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  site: datadoghq.com
  clusterName: default
  processAgent:
    enabled: true
    processCollection: true
  clusterAgent:
    enabled: true
    metricsProvider:
      enabled: true
  orchestratorExplorer:
    enabled: true
  kubeStateMetricsCore:
    enabled: true
  containerImageCollection:
    enabled: true
  sbom:
    containerImage:
      enabled: true
