name: Deploy DataDog into Kubernetes
on:
  workflow_dispatch:

env:
  DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}

jobs:
  Explore-GitHub-Actions:
    runs-on: gha-runner-scale-set
    steps:
    - run: sudo apt-get -y update
    - run: sudo apt-get -y install zip
    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '${'
        tokenSuffix: '}'
        files: '["**/*.yaml"]'
    - name: Helm tool installer
      uses: Azure/setup-helm@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: helm repo add datadog https://helm.datadoghq.com
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods
