name: Deploy DataDog into Kubernetes
on:
  workflow_dispatch:

env:
  DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}

jobs:
  Deploy-Cluster:
    runs-on: gha-runner-scale-set
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: ls
    - run: sudo apt-get -y update
    - run: sudo apt-get -y install zip
    - run: echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > kubeconfig.yaml
    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '${'
        tokenSuffix: '}'
        files: '["**/*.yaml"]'
    - name: Helm tool installer
      uses: Azure/setup-helm@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: helm repo add datadog https://helm.datadoghq.com

    - run: ls

    - run: helm upgrade --install --cleanup-on-fail --namespace default datadog-agent -f values.yaml --set targetSystem=linux datadog/datadog --kubeconfig kubeconfig.yaml
  
